### ISSUE TITLE
Motor not working

### ISSUE THREAD

**Issue by lvjonok** [mtmal/jetracer_cpp#1]
Hello!

Thank you for development of alternative control to jetracer cars. I managed to successfully build your repository. But when I run `jetracer_app` only steering works.

I thought that it might be problem with car, but original code on python works well. Could you provide some information what could be the problem and how to fix it?

**Comment by mtmal** [comment]
Hi,

That's a strange one I must say. I double-checked and I haven't experienced any issues on my side. Have you tried testing wheels when the car is lifted, so that there is no traction? If you used car on ground with high friction, your throttle gain may be too small. In the test I hard-coded it to 0.3, but typically use 0.5 in other applications. Perhaps you can try increasing it to 1 (maximum value)?

Do you use Waveshare's JetRacer? If not, there might be a different PCA9685 address for throttle control (0x60 in my case) or different I2C frequency (1600 Hz). Both of these are hard-coded in NvidiaRacer.cpp. Lastly, your drive motors controller can be wired differently. Take a look at specific PCA channels which duty cycles are set in setThrottle function.

I hope that helps!

**Comment by lvjonok** [comment]
It seems I have found a problem. It lies in definition of jetracer from waveshare) I have Pro version which has this example class in python:

```python
class NvidiaRacecar(Racecar):
    
    i2c_address = traitlets.Integer(default_value=0x40)
    steering_gain = traitlets.Float(default_value=-0.65)
    steering_offset = traitlets.Float(default_value=0)
    steering_channel = traitlets.Integer(default_value=0)
    throttle_gain = traitlets.Float(default_value=0.8)
    throttle_channel = traitlets.Integer(default_value=1)
    
    def __init__(self, *args, **kwargs):
        super(NvidiaRacecar, self).__init__(*args, **kwargs)
        self.kit = ServoKit(channels=16, address=self.i2c_address)
        self.steering_motor = self.kit.continuous_servo[self.steering_channel]
        self.throttle_motor = self.kit.continuous_servo[self.throttle_channel]
    
    @traitlets.observe('steering')
    def _on_steering(self, change):
        self.steering_motor.throttle = change['new'] * self.steering_gain + self.steering_offset
    
    @traitlets.observe('throttle')
    def _on_throttle(self, change):
        self.throttle_motor.throttle = change['new'] * self.throttle_gain
```

As you see there is only one i2c address and it uses different channels inside. I think that is the problem and you code works, but just for different model of car. Thank you for your help! Maybe if I will work your code a bit there will be a PR from my side with new class.

**Comment by mtmal** [comment]
Ah, got it. I pushed an update that should take pro version into account, but you need to pass -DJETRACER_PRO flag via cmake, for example
`cmake .. -DJETRACER_PRO`

Let me know if that works, I'm curious to see!

**Comment by lvjonok** [comment]
That actually works! I mean at least motor is working with this code. There are still problems like:
- initialization is not completed when I run `racer.initialise()`. Several first commands do not move motors, I think it is some problem of blocking/non-blocking operations.
- when I pass 0 throttle to stop it is not actually 0, motors still keep running

I think this is enough to work with. I will try to look into this problems myself and will keep you updated!
